{% set name = "dem2points" %}
{% set version = "master" %}
{% set commit = "b05d61618a01d9ab700f11117b47264eddb7820f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/OpenDroneMap/dem2points/archive/{{ commit }}.tar.gz
  sha256: dfde508afa4d4f7f6b2281dba9d88ceb0113068bea2ebfd33ee6d9f7dbb66c63

build:
    number: 0

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - libgdal {{ libgdal }}

test:
  commands:
    - test -f $PREFIX/bin/dem2points

about:
  home: https://github.com/OpenDroneMap/dem2points
  license: GPL 3
  summary: Extract 3D points from digital elevation models

extra:
  recipe-maintainers:
    - v-turin
